use rhuss sti s2i-java image as inspiration

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -1,88 +1,136 @@
 #!/bin/bash
 
-# restore maven dependencies downloaded in a previous build,
-# so they do not have to be downloaded again.
-# /opt/s2i/destination/artifacts will only be present in the incremental build scenario
-# in which the target image name is an existing docker image which contains
-# dependencies from a prior build execution.
-function restore_saved_artifacts() {
-  if [ "$(ls /opt/s2i/destination/artifacts/ 2>/dev/null)" ]; then
-    echo -n "Restoring saved artifacts from prior build..."
-    mv /opt/s2i/destination/artifacts/* $HOME/.
+# Global S2I variable setup
+source `dirname "$0"`/s2i-setup
+
+# Maven arguments setting up the environment
+maven_env_args="-Dmaven.repo.local=${S2I_ARTIFACTS_DIR}/m2"
+
+# =========================================================================
+# Helper functions:
+
+function check_error() {
+  local label=$1
+  local error=$2
+  if [ ${error} -ne 0 ]; then
+    echo "Aborting due to error code $error for $label"
+    exit ${error}
   fi
 }
 
-# Source code provided to S2I is at ${HOME}
-LOCAL_SOURCE_DIR=${HOME}
-mkdir -p $LOCAL_SOURCE_DIR
+function get_output_dir() {
+  local dir=""
 
-# Resulting files will be deployed to ${JAVA_APP_DIR}
-DEPLOY_DIR=${JAVA_APP_DIR}
-mkdir -p $DEPLOY_DIR
-
-# Copy the source for compilation
-cp -Rf /opt/s2i/destination/src/. $LOCAL_SOURCE_DIR
-chgrp -R 1001 $LOCAL_SOURCE_DIR
-chmod -R g+rw $LOCAL_SOURCE_DIR
-
-# If a pom.xml is present, this is a normal build scenario
-# so run maven.
-if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
-  # restore any maven dependencies which will be present if this is an
-  # incremental build
-  restore_saved_artifacts
-
-  pushd $LOCAL_SOURCE_DIR &> /dev/null
-
-  if [ -z "$MAVEN_ARGS" ]; then
-    export MAVEN_ARGS="package -Popenshift -DskipTests"
-  fi
-  if [ -z "$MAVEN_ARGS_APPEND" ]; then
-    export MAVEN_ARGS="$MAVEN_ARGS $MAVEN_ARGS_APPEND"
-  fi
-  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
-
-  mvn --version
-  mvn $MAVEN_ARGS
-
-  ERR=$?
-  if [ $ERR -ne 0 ]; then
-    echo "Aborting due to error code $ERR from mvn package"
-    exit $ERR
+  # If multi module build and no ARTIFACT_DIR is set --> error
+  if [ x"${ARTIFACT_DIR}" = x ]; then
+    echo " ${MAVEN_ARGS} ${MAVEN_ARGS_APPEND}" | grep -q ' -pl'
+    if [ $? -eq 0 ]; then
+       echo "ARTIFACT_DIR must be set for multi module Maven builds"
+       exit 1
+    fi
+    dir="${S2I_SOURCE_DIR}/target"
+  else
+    if [ "${ARTIFACT_DIR:0:1}" = "/" ]; then
+       echo "ARTIFACT_DIR \"${ARTIFACT_DIR}\" must not be absolute but relative to the source directory"
+       exit 1
+    fi
+    dir="${S2I_SOURCE_DIR}/${ARTIFACT_DIR}"
   fi
 
-  echo "Copying built war files into $DEPLOY_DIR for later deployment..."
-  popd &> /dev/null
+  # Normalize dir
+  dir=$(echo ${dir} | tr -s /)
+  dir=${dir%/}
+  # The parent must exist but target/ won't exist yet
+  if [ ! -d $(dirname "${dir}"}) ]; then
+    echo "Please specify an existing build directory ARTIFACT_DIR (tried '$(dirname "${dir}")' which does not exist)"
+    exit 1
+  fi
+  echo ${dir}
+}
+
+function copy_dir() {
+  local src=$1
+  local dest=$2
+
+  cp -r ${src}/* ${dest}
+  check_error "copying ${src} to ${dest}" $?
+}
+
+function setup_maven() {
+  if [ -f "${S2I_SOURCE_DIR}/configuration/settings.xml" ]; then
+    maven_env_args="${maven_env_args} -s ${S2I_SOURCE_DIR}/configuration/settings.xml"
+    echo "Using custom maven settings from ${S2I_SOURCE_DIR}/configuration/settings.xml"
+  fi
+}
+
+function build_maven() {
+  # Where artifacts are created during build
+  local build_dir=$1
+
+  # Where to put the artifacts
+  local app_dir=$2
+
+  # Use main class if given
+  local hawtapp_arg=""
+  if [ x"${JAVA_MAIN_CLASS}" != x ]; then
+    hawtapp_arg="-Dhawt-app.javaMainClass=${JAVA_MAIN_CLASS} io.fabric8:hawt-app-maven-plugin:${HAWTAPP_VERSION}:build"
+  fi
+
+  # Default args: no tests, if a module is specified, only build this module
+  local maven_args=${MAVEN_ARGS:-package -DskipTests ${hawtapp_arg} -e}
+
+  echo "Found pom.xml ... "
+  echo "Running 'mvn ${maven_env_args} ${maven_args} ${MAVEN_ARGS_APPEND}'"
+
+  local old_dir=$(pwd)
+  cd ${S2I_SOURCE_DIR}
+  check_error "changing directory to ${S2I_SOURCE_DIR}" $?
+
+  # =========
+  # Run Maven
+  mvn ${maven_env_args} --version
+  mvn ${maven_env_args} ${maven_args} ${MAVEN_ARGS_APPEND}
+  check_error "Maven build" $?
+
+  # ======================
+  # After-build validation
+  if [ ! -d "${build_dir}/hawt-app" ] && [ x"${JAVA_MAIN_CLASS}" = x ]; then
+    echo "No JAVA_MAIN_CLASS specified and no hawt-app-maven-plugin configured in the pom.xml"
+    exit 1
+  fi
+
+  # ==============
+  # Copy artifacts
+  echo "Copying Maven artifacts from ${build_dir}/hawt-app to ${app_dir} ..."
+  copy_dir "${build_dir}/hawt-app" ${app_dir}
+
+  # ======================
+  # Remove repo if desired
+  if [ "x${MAVEN_CLEAR_REPO}" != "x" ]; then
+    rm -rf "${S2I_ARTIFACTS_DIR}/m2"
+    check_error "Cannot remove local Maven repository ${S2I_ARTIFACTS_DIR}/m2" $?
+  fi
+
+  cd ${old_dir}
+}
+
+# =========================================================================
+# Main
+
+echo "=================================================================="
+echo "Starting S2I Java Build ....."
+build_dir=$(get_output_dir)
+check_error "Cannot get output dir: $build_dir" $?
+if [ -f "${S2I_SOURCE_DIR}/pom.xml" ]; then
+  echo "Maven build detected"
+  # If a pom.xml is present use maven
+  setup_maven
+  build_maven ${build_dir} ${DEPLOYMENTS_DIR}
 else
-  echo "Copying binaries in source directory into $DEPLOY_DIR for later deployment..."
+  binary_dir="${ARTIFACT_DIR:-${S2I_SOURCE_DIR}/deployments}"
+  # Assuming that the source already contains compiled artefacts
+  echo "Copying binaries from ${binary_dir} to ${S2I_ARTIFACTS_DIR} ..."
+  copy_dir ${binary_dir} ${DEPLOYMENTS_DIR}
 fi
 
-if [ -d $LOCAL_SOURCE_DIR/target ]; then
-  cp $LOCAL_SOURCE_DIR/target/*.jar $DEPLOY_DIR >& /dev/null
-  chgrp -R 1001 $DEPLOY_DIR
-  chmod -R g+rw $DEPLOY_DIR
-fi
-
-if [ -d $LOCAL_SOURCE_DIR/deployments ]; then
-  cp $LOCAL_SOURCE_DIR/deployments/*.jar $DEPLOY_DIR >& /dev/null
-  chgrp -R 1001 $DEPLOY_DIR
-  chmod -R g+rw $DEPLOY_DIR
-fi
-
-if [ -d $LOCAL_SOURCE_DIR/etc ]; then
-  echo "Copying etc files from project..."
-  cp $LOCAL_SOURCE_DIR/etc/*.jar $DEPLOY_DIR/etc >& /dev/null
-  chgrp -R 1001 $DEPLOY_DIR/etc
-  chmod -R g+rw $DEPLOY_DIR/etc
-fi
-
-if [ -d $LOCAL_SOURCE_DIR/lib ]; then
-  echo "Copying lib files from project..."
-  cp $LOCAL_SOURCE_DIR/lib/*.jar $DEPLOY_DIR/lib >& /dev/null
-  chgrp -R 1001 $DEPLOY_DIR/lib
-  chmod -R g+rw $DEPLOY_DIR/lib
-fi
-
-echo "...done"
-
-exit $rc
+echo "... done"
